# gen_rv32.py — generate an RV32I CPU as a HATTAR NAND netlist.
import sys

RING = 384
PERIOD = 2 * RING

class G:
    def __init__(self):
        self.lines, self.cnt, self.inits = [], 0, []
    def raw(self, s): self.lines.append(s)
    def name(self, p="t"):
        self.cnt += 1
        return f"{p}{self.cnt}"
    def gate(self, out, ins):
        assert 1 <= len(ins) <= 16, (out, len(ins))
        self.raw(f"{out} : T- " + " ".join(ins))
        return out
    def NAND(self, *ins): return self.gate(self.name(), list(ins))
    def NOT(self, a): return self.NAND(a)
    def AND(self, ins):
        ins = list(ins)
        while len(ins) > 16:
            ins = [self.NOT(self.NAND(*ins[i:i+16])) for i in range(0, len(ins), 16)]
        return self.NOT(self.NAND(*ins))
    def OR(self, ins):
        ins = list(ins)
        while len(ins) > 16:
            ins = [self.NAND(*[self.NOT(x) for x in ins[i:i+16]])
                   for i in range(0, len(ins), 16)]
        return self.NAND(*[self.NOT(x) for x in ins])
    def XOR(self, a, b):
        n = self.NAND(a, b)
        return self.NAND(self.NAND(a, n), self.NAND(b, n))
    def MUX2(self, s, sn, a, b):
        return self.NAND(self.NAND(s, a), self.NAND(sn, b))
    def latch(self, D, Dn, EN, init=0, nm=None):
        q = nm or self.name("q"); qb = q + "b"
        sb = self.NAND(D, EN); rb = self.NAND(Dn, EN)
        self.gate(q, [sb, qb]); self.gate(qb, [rb, q])
        self.inits += [(q, init), (qb, 1 - init)]
        return q
    def latch_bus(self, Ds, EN, init=0, pfx="L"):
        return [self.latch(d, self.NOT(d), EN, (init >> i) & 1,
                           nm=f"{pfx}{i}") for i, d in enumerate(Ds)]
    def ADD(self, A, B, cin):
        s, c = [], cin
        for a, b in zip(A, B):
            x = self.XOR(a, b)
            s.append(self.XOR(x, c))
            c = self.NAND(self.NAND(a, b), self.NAND(x, c))
        return s, c
    def win(self, set_pair, rst_pair, nm):
        q, qb = nm, nm + "b"
        self.gate(q, [f"i{set_pair % RING}", qb])
        self.gate(qb, [f"i{rst_pair % RING}", q])
        self.inits += [(q, 0), (qb, 1)]
        return q

g = G()
g.raw("# RV32I CPU — NAND netlist for HATTAR-PC (generated by gen_rv32.py)")
g.raw("hz 20000000")

g.raw("gnd :")
ZERO = "gnd"
ONE = g.NOT(ZERO)

for k in range(RING):
    g.gate(f"i{k}", [f"r{k}"])
    g.gate(f"r{(k + 1) % RING}", [f"i{k}"])
for k in range(RING):
    g.inits.append((f"r{k}", 0))

def W(a, b, nm): return g.win(a // 2, b // 2, nm)

WF1 = W(52, 100, "WF1"); WF2 = W(100, 148, "WF2"); WF3 = W(148, 196, "WF3")
IR0E = W(40, 52, "IR0E"); IR1E = W(88, 100, "IR1E")
IR2E = W(136, 148, "IR2E"); IR3E = W(184, 196, "IR3E")
EAPH = W(340, 700, "EAPH")
WM0 = W(340, 404, "WM0"); WM1 = W(404, 468, "WM1")
WM2 = W(468, 532, "WM2"); WM3 = W(532, 596, "WM3")
MEN = [W(388, 400, "MEN0"), W(452, 464, "MEN1"),
       W(516, 528, "MEN2"), W(580, 592, "MEN3")]
WB0 = W(648, 664, "WB0"); WB1 = W(696, 712, "WB1")

MDOUT = [f"md{i}" for i in range(8)]
IR = []
for by, en in enumerate([IR0E, IR1E, IR2E, IR3E]):
    IR += g.latch_bus(MDOUT, en, 0, pfx=f"ir{by}_")
IRN = [g.NOT(b) for b in IR]

def is_op(bits7):
    lits = [IR[i] if (bits7 >> i) & 1 else IRN[i] for i in range(7)]
    return g.AND(lits)

OP    = is_op(0b0110011); OPIMM = is_op(0b0010011)
LOAD  = is_op(0b0000011); STORE = is_op(0b0100011)
BR    = is_op(0b1100011); LUI   = is_op(0b0110111)
AUIPC = is_op(0b0010111); JAL   = is_op(0b1101111)
JALR  = is_op(0b1100111)

F3 = IR[12:15]; F3N = IRN[12:15]
f3 = [g.AND([F3[j] if (v >> j) & 1 else F3N[j] for j in range(3)])
      for v in range(8)]
F7B5, F7B5N = IR[30], IRN[30]

def dec5(bits, pfx):
    b, bn = bits, [g.NOT(x) for x in bits]
    return [g.NOT(g.gate(f"{pfx}n{v}",
             [b[j] if (v >> j) & 1 else bn[j] for j in range(5)]))
            for v in range(32)]

RS1D = dec5(IR[15:20], "rs1d")
RS2D = dec5(IR[20:25], "rs2d")
RDD  = dec5(IR[7:12],  "rdd")

has_rd = g.OR([OP, OPIMM, LOAD, LUI, AUIPC, JAL, JALR])
wpulse = g.AND([WB1, has_rd])
WD  = [f"wd{i}" for i in range(32)]
WDN = [f"wdn{i}" for i in range(32)]
REG = {}
for v in range(1, 32):
    env = g.AND([RDD[v], wpulse])
    row = []
    for i in range(32):
        q = f"x{v}_{i}"; qb = q + "b"
        sb = g.NAND(WD[i], env); rb = g.NAND(WDN[i], env)
        g.gate(q, [sb, qb]); g.gate(qb, [rb, q])
        g.inits += [(q, 0), (qb, 1)]
        row.append(q)
    REG[v] = row

def read_port(dec, pfx):
    out = []
    for i in range(32):
        terms = [g.NAND(dec[v], REG[v][i]) for v in range(1, 32)]
        o = g.OR([g.NOT(t) for t in terms])
        out.append(o)
    return out

RS1 = read_port(RS1D, "rs1v")
RS2 = read_port(RS2D, "rs2v")

sgn = IR[31]
immI = [IR[20 + i] for i in range(11)] + [sgn] * 21
immS = [IR[7 + i] for i in range(5)] + [IR[25 + i] for i in range(6)] + [sgn] * 21
immB = [ZERO] + [IR[8 + i] for i in range(4)] + [IR[25 + i] for i in range(6)] \
     + [IR[7]] + [sgn] * 20
immU = [ZERO] * 12 + [IR[i] for i in range(12, 32)]
immJ = [ZERO] + [IR[21 + i] for i in range(10)] + [IR[20]] \
     + [IR[12 + i] for i in range(8)] + [sgn] * 12

STOREN = g.NOT(STORE)
imm_alu = [g.MUX2(STORE, STOREN, s, i) for s, i in zip(immS, immI)]

breg = g.OR([OP, BR]); bregn = g.NOT(breg)
B = [g.MUX2(breg, bregn, r, m) for r, m in zip(RS2, imm_alu)]
is_slt = g.AND([g.OR([OP, OPIMM]), g.OR([f3[2], f3[3]])])
sub = g.OR([BR, is_slt, g.AND([OP, f3[0], F7B5])])
BX = [g.XOR(b, sub) for b in B]
SUM, COUT = g.ADD(RS1, BX, sub)
ltu = g.NOT(COUT)
zero = g.AND([g.NOT(s) for s in SUM])
sdif = g.XOR(RS1[31], B[31])
lt = g.MUX2(sdif, g.NOT(sdif), RS1[31], SUM[31])

XORV = [g.XOR(a, b) for a, b in zip(RS1, B)]
ORV  = [g.NAND(g.NOT(a), g.NOT(b)) for a, b in zip(RS1, B)]
ANDV = [g.NOT(g.NAND(a, b)) for a, b in zip(RS1, B)]

is_sll = f3[1]; is_slln = g.NOT(is_sll)
is_sra = g.AND([f3[5], F7B5])
fill = g.AND([is_sra, RS1[31]])
sh = [(B[k], g.NOT(B[k])) for k in range(5)]
cur = [g.MUX2(is_sll, is_slln, RS1[31 - i], RS1[i]) for i in range(32)]
for k in range(5):
    s, sn = sh[k]; step = 1 << k
    cur = [g.MUX2(s, sn, cur[i + step] if i + step < 32 else fill, cur[i])
           for i in range(32)]
SHIFT = [g.MUX2(is_sll, is_slln, cur[31 - i], cur[i]) for i in range(32)]

ALURES = []
for i in range(32):
    slt_v = lt if i == 0 else ZERO
    sltu_v = ltu if i == 0 else ZERO
    vals = [SUM[i], SHIFT[i], slt_v, sltu_v, XORV[i], SHIFT[i], ORV[i], ANDV[i]]
    ALURES.append(g.OR([g.NOT(g.NAND(f3[k], vals[k])) for k in range(8)]))

zn, ltn, ltun = g.NOT(zero), g.NOT(lt), g.NOT(ltu)
conds = [zero, zn, ZERO, ZERO, lt, ltn, ltu, ltun]
taken = g.AND([BR, g.OR([g.NOT(g.NAND(f3[k], conds[k])) for k in range(8)])])

PC = [f"pc{i}" for i in range(32)]
C4 = [ZERO, ZERO, ONE] + [ZERO] * 29
PCINC, _ = g.ADD(PC, C4, ZERO)
JALN = g.NOT(JAL); AUIPCN = g.NOT(AUIPC)
pcimm = [g.MUX2(JAL, JALN, j, g.MUX2(AUIPC, AUIPCN, u, b))
         for j, u, b in zip(immJ, immU, immB)]
PCADD, _ = g.ADD(PC, pcimm, ZERO)
jtb = g.OR([JAL, taken]); jtbn = g.NOT(jtb)
T1 = [g.MUX2(jtb, jtbn, a, i) for a, i in zip(PCADD, PCINC)]
JALRN = g.NOT(JALR)
NEXTPC = [g.MUX2(JALR, JALRN,
                 g.AND([SUM[i], JALRN]) if i == 0 else SUM[i], T1[i])
          for i in range(32)]
NEXTPC[0] = g.MUX2(JALR, JALRN, ZERO, T1[0])

EAPHN = g.NOT(EAPH)
base = [g.MUX2(EAPH, EAPHN, SUM[i], PC[i]) for i in range(16)]
k0 = g.OR([WF1, WF3, WM1, WM3]); k1 = g.OR([WF2, WF3, WM2, WM3])
KOFS = [k0, k1] + [ZERO] * 14
MADDR, _ = g.ADD(base, KOFS, ZERO)
g.raw("maddr " + " ".join(MADDR))
g.raw("mdout " + " ".join(MDOUT))

lane_en = [STORE,
           g.AND([STORE, g.OR([f3[1], f3[2]])]),
           g.AND([STORE, f3[2]]),
           g.AND([STORE, f3[2]])]
WE = g.OR([g.NOT(g.NAND(MEN[k], lane_en[k])) for k in range(4)])
g.inits.append((WE, 0))        # keep RAM writes off while logic settles
g.raw(f"mwe {WE}")
MDIN = [g.OR([g.NOT(g.NAND(w, RS2[k * 8 + i]))
              for k, w in enumerate([WM0, WM1, WM2, WM3])])
        for i in range(8)]
g.raw("mdin " + " ".join(MDIN))

LB = [g.latch_bus(MDOUT, MEN[k], 0, pfx=f"lb{k}_") for k in range(4)]

sB0, sB1 = LB[0][7], LB[1][7]
lb_s, lh_s, lw_s = f3[0], f3[1], f3[2]
lh_any = g.OR([f3[1], f3[2], f3[5]])
LDEXT = list(LB[0])
for i in range(8, 16):
    LDEXT.append(g.OR([g.NOT(g.NAND(lh_any, LB[1][i - 8])),
                       g.NOT(g.NAND(lb_s, sB0))]))
for i in range(16, 32):
    hi = LB[2][i - 16] if i < 24 else LB[3][i - 24]
    LDEXT.append(g.OR([g.NOT(g.NAND(lw_s, hi)),
                       g.NOT(g.NAND(lb_s, sB0)),
                       g.NOT(g.NAND(lh_s, sB1))]))

LOADN, LUIN = g.NOT(LOAD), g.NOT(LUI)
jj = g.OR([JAL, JALR]); jjn = g.NOT(jj)
WDATA = [g.MUX2(LOAD, LOADN, LDEXT[i],
         g.MUX2(LUI, LUIN, immU[i],
         g.MUX2(AUIPC, AUIPCN, PCADD[i],
         g.MUX2(jj, jjn, PCINC[i], ALURES[i])))) for i in range(32)]

for i in range(32):
    d = WDATA[i]; dn = g.NOT(d)
    sb = g.NAND(d, WB0); rb = g.NAND(dn, WB0)
    g.gate(WD[i], [sb, f"wdq{i}"]); g.gate(f"wdq{i}", [rb, WD[i]])
    g.gate(WDN[i], [WD[i]])
    g.inits += [(WD[i], 0), (f"wdq{i}", 1)]
PCN = g.latch_bus(NEXTPC, WB0, 0, pfx="pcn")
PCNN = [g.NOT(x) for x in PCN]
for i in range(32):
    sb = g.NAND(PCN[i], WB1); rb = g.NAND(PCNN[i], WB1)
    g.gate(PC[i], [sb, f"pcq{i}"]); g.gate(f"pcq{i}", [rb, PC[i]])
    g.inits += [(PC[i], 0), (f"pcq{i}", 1)]

def finalize(mem_bytes, extra=""):
    out = list(g.lines)
    if extra: out.append(extra)
    CH = 96
    for a0 in range(0, len(mem_bytes), CH):
        chunk = mem_bytes[a0:a0 + CH]
        out.append(f"mem {a0} " + " ".join(f"{b:02x}" for b in chunk))
    for n, v in g.inits: out.append(f"{n} ! {v}")
    out.append("t 12")
    for n, _ in g.inits: out.append(f"{n} ! -")
    out.append("r0 !")                    # 2-tick-wide pulse: SR window
    out.append("t 1")                     # latches need >=2 ticks of set
    out.append("r0 !")
    out.append("w r0 WB1 " + " ".join(f"pc{i}" for i in range(2, 8)))
    return "\n".join(out) + "\n"

R = {f"x{i}": i for i in range(32)}
def enc_r(f7, f3v, op, rd, r1, r2):
    return (f7 << 25) | (r2 << 20) | (r1 << 15) | (f3v << 12) | (rd << 7) | op
def enc_i(f3v, op, rd, r1, imm):
    return ((imm & 0xFFF) << 20) | (r1 << 15) | (f3v << 12) | (rd << 7) | op
def enc_s(f3v, rs1, rs2, imm):
    return (((imm >> 5) & 0x7F) << 25) | (rs2 << 20) | (rs1 << 15) \
         | (f3v << 12) | ((imm & 0x1F) << 7) | 0b0100011
def enc_b(f3v, rs1, rs2, imm):
    return (((imm >> 12) & 1) << 31) | (((imm >> 5) & 0x3F) << 25) \
         | (rs2 << 20) | (rs1 << 15) | (f3v << 12) \
         | (((imm >> 1) & 0xF) << 8) | (((imm >> 11) & 1) << 7) | 0b1100011
def enc_u(op, rd, imm): return (imm & 0xFFFFF000) | (rd << 7) | op
def enc_j(rd, imm):
    return (((imm >> 20) & 1) << 31) | (((imm >> 1) & 0x3FF) << 21) \
         | (((imm >> 11) & 1) << 20) | (((imm >> 12) & 0xFF) << 12) \
         | (rd << 7) | 0b1101111

OPS = {
 'add':('r',0,0),'sub':('r',0x20,0),'sll':('r',0,1),'slt':('r',0,2),
 'sltu':('r',0,3),'xor':('r',0,4),'srl':('r',0,5),'sra':('r',0x20,5),
 'or':('r',0,6),'and':('r',0,7),
 'addi':('i',0b0010011,0),'slti':('i',0b0010011,2),'sltiu':('i',0b0010011,3),
 'xori':('i',0b0010011,4),'ori':('i',0b0010011,6),'andi':('i',0b0010011,7),
 'slli':('sh',0,1),'srli':('sh',0,5),'srai':('sh',0x20,5),
 'lb':('l',0),'lh':('l',1),'lw':('l',2),'lbu':('l',4),'lhu':('l',5),
 'sb':('s',0),'sh':('s',1),'sw':('s',2),
 'beq':('b',0),'bne':('b',1),'blt':('b',4),'bge':('b',5),
 'bltu':('b',6),'bgeu':('b',7),
 'jal':('j',),'jalr':('jr',),'lui':('u',0b0110111),'auipc':('u',0b0010111),
}

def assemble(src):
    lines = [l.split('#')[0].strip() for l in src.strip().splitlines()]
    lines = [l for l in lines if l]
    labels, pc = {}, 0
    prog = []
    for l in lines:
        if l.endswith(':'): labels[l[:-1]] = pc
        else: prog.append((pc, l)); pc += 4
    words = []
    for pc, l in prog:
        p = l.replace(',', ' ').split()
        m = p[0]; kind = OPS[m]
        def rimm(x): return labels[x] - pc if x in labels else int(x, 0)
        if kind[0] == 'r':
            words.append(enc_r(kind[1], kind[2], 0b0110011, R[p[1]], R[p[2]], R[p[3]]))
        elif kind[0] == 'i':
            words.append(enc_i(kind[2], kind[1], R[p[1]], R[p[2]], int(p[3], 0)))
        elif kind[0] == 'sh':
            imm = (kind[1] << 5) | (int(p[3], 0) & 31)
            words.append(enc_i(kind[2], 0b0010011, R[p[1]], R[p[2]], imm))
        elif kind[0] == 'l':
            off, rs1 = p[2].rstrip(')').split('(')
            words.append(enc_i(kind[1], 0b0000011, R[p[1]], R[rs1], int(off, 0)))
        elif kind[0] == 's':
            off, rs1 = p[2].rstrip(')').split('(')
            words.append(enc_s(kind[1], R[rs1], R[p[1]], int(off, 0)))
        elif kind[0] == 'b':
            words.append(enc_b(kind[1], R[p[1]], R[p[2]], rimm(p[3])))
        elif kind[0] == 'j':
            words.append(enc_j(R[p[1]], rimm(p[2])))
        elif kind[0] == 'jr':
            words.append(enc_i(0, 0b1100111, R[p[1]], R[p[2]], int(p[3], 0)))
        elif kind[0] == 'u':
            words.append(enc_u(kind[1], R[p[1]], int(p[2], 0) & 0xFFFFF000))
    by = []
    for w in words:
        by += [w & 0xFF, (w >> 8) & 0xFF, (w >> 16) & 0xFF, (w >> 24) & 0xFF]
    return by

def golden(mem_bytes, max_instr=200000):
    M = bytearray(65536)
    M[:len(mem_bytes)] = bytes(mem_bytes)
    x = [0] * 32
    pc, n = 0, 0
    sx = lambda v, b: v - (1 << b) if v & (1 << (b - 1)) else v
    while n < max_instr:
        w = int.from_bytes(M[pc & 0xFFFF: (pc & 0xFFFF) + 4], 'little')
        op, rd = w & 0x7F, (w >> 7) & 31
        f3v, r1, r2 = (w >> 12) & 7, (w >> 15) & 31, (w >> 20) & 31
        f7 = w >> 25
        iI = sx(w >> 20, 12); iS = sx(((w >> 25) << 5) | ((w >> 7) & 31), 12)
        iB = sx((((w >> 31) & 1) << 12) | (((w >> 7) & 1) << 11)
                | (((w >> 25) & 63) << 5) | (((w >> 8) & 15) << 1), 13)
        iU = w & 0xFFFFF000
        iJ = sx((((w >> 31) & 1) << 20) | (((w >> 12) & 255) << 12)
                | (((w >> 20) & 1) << 11) | (((w >> 21) & 1023) << 1), 21)
        a, b = x[r1], x[r2]
        npc = (pc + 4) & 0xFFFFFFFF
        res = None
        u32 = lambda v: v & 0xFFFFFFFF
        s32 = lambda v: sx(v & 0xFFFFFFFF, 32)
        if op == 0b0110011 or op == 0b0010011:
            bb = b if op == 0b0110011 else u32(iI)
            sh = bb & 31
            if f3v == 0:
                res = u32(a - bb) if (op == 0b0110011 and f7 == 0x20) else u32(a + bb)
            elif f3v == 1: res = u32(a << sh)
            elif f3v == 2: res = 1 if s32(a) < s32(bb) else 0
            elif f3v == 3: res = 1 if u32(a) < u32(bb) else 0
            elif f3v == 4: res = a ^ bb
            elif f3v == 5: res = u32(s32(a) >> sh) if f7 == 0x20 else u32(a) >> sh
            elif f3v == 6: res = a | bb
            elif f3v == 7: res = a & bb
        elif op == 0b0000011:
            ea = u32(a + iI) & 0xFFFF
            if f3v == 0: res = u32(sx(M[ea], 8))
            elif f3v == 1: res = u32(sx(M[ea] | (M[(ea+1)&0xFFFF] << 8), 16))
            elif f3v == 2: res = int.from_bytes(
                bytes(M[(ea+i)&0xFFFF] for i in range(4)), 'little')
            elif f3v == 4: res = M[ea]
            elif f3v == 5: res = M[ea] | (M[(ea+1)&0xFFFF] << 8)
        elif op == 0b0100011:
            ea = u32(a + iS) & 0xFFFF
            nby = {0:1, 1:2, 2:4}[f3v]
            for i in range(nby): M[(ea+i) & 0xFFFF] = (b >> (8*i)) & 0xFF
        elif op == 0b1100011:
            t = {0: a == b, 1: a != b, 4: s32(a) < s32(b), 5: s32(a) >= s32(b),
                 6: u32(a) < u32(b), 7: u32(a) >= u32(b)}[f3v]
            if t: npc = u32(pc + iB)
        elif op == 0b0110111: res = iU
        elif op == 0b0010111: res = u32(pc + iU)
        elif op == 0b1101111: res = u32(pc + 4); npc = u32(pc + iJ)
        elif op == 0b1100111: res = u32(pc + 4); npc = u32(a + iI) & ~1
        if res is not None and rd: x[rd] = u32(res)
        if npc == pc: break
        pc, n = npc, n + 1
    return M, n, x

if __name__ == "__main__":
    asm_path, out_path = sys.argv[1], sys.argv[2]
    prog = assemble(open(asm_path).read())
    M, n, x = golden(prog)
    txt = finalize(prog)
    open(out_path, "w").write(txt)
    open(out_path + ".golden", "wb").write(bytes(M))
    import json
    open(out_path + ".regs", "w").write(json.dumps(x))
    nodes = sum(1 for l in txt.splitlines() if " : " in l or l == "gnd :")
    print(f"nodes={nodes}  instrs={len(prog)//4}  golden ran {n} instructions")
    print(f"ticks needed ~ {(n + 4) * PERIOD}")
